export const COMMERCIAL_LANES = [
  {
    id: 'aix-governance-sprint',
    name: 'AIX Governance Sprint',
    buyer: 'Enterprise AI, platform, security, and governance teams',
    paidMotion: 'Fixed-scope governance sprint, adoption evidence bundle, or private deployment add-on',
    tagline: 'RAG, policy gates, DLP, eval, KPI, and private deployment readiness without unsupported AI transformation claims.',
    primaryRepos: ['aix-pilot', 'enterprise-llm-adoption-kit', 'llm-onprem-deployment-kit'],
    supportRepos: ['ai-security-redteam-lab', 'ai-agent-production-lab', 'tool-call-finetune-lab'],
    proofSignal: 'Governance · eval · private deployment',
    ctaUrl: 'https://github.com/KIM3310/KIM3310/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+enterprise+AI+governance',
  },
  {
    id: 'stagepilot-reliability-lab',
    name: 'StagePilot Reliability Lab',
    buyer: 'AI product teams and agent platform engineers',
    paidMotion: 'Private benchmark scenarios, hosted regression dashboard, or adapter implementation support',
    tagline: 'Tool-call parsing, retries, traces, benchmark reports, and provider routing for teams shipping real agent systems.',
    primaryRepos: ['stage-pilot', 'agent-runtime-go', 'agent-orchestration-benchmark'],
    supportRepos: ['multi-cli-pilot', 'claude-agent-cookbook', 'cohere-agent-cookbook'],
    proofSignal: 'Traces · retries · benchmark reports',
    ctaUrl: 'https://github.com/KIM3310/KIM3310/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+agent+reliability',
  },
  {
    id: 'aegisops-response-room',
    name: 'AegisOps Response Room',
    buyer: 'SOC, NOC, IDC, MSP, and infrastructure operations teams',
    paidMotion: 'Tabletop scenario workspace, incident replay pack, or recurring service assurance report',
    tagline: 'Incident replay, service maps, tabletop response, handoff boards, and SLA evidence for operator teams.',
    primaryRepos: ['AegisOps', 'security-threat-response-workbench', 'nw-service-assurance-workbench'],
    supportRepos: ['ops-reliability-workbench', 'honeypot', 'Aegis-Air'],
    proofSignal: 'Incident replay · handoff · SLA evidence',
    ctaUrl: 'https://github.com/KIM3310/KIM3310/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+security+operations',
  },
  {
    id: 'nexus-data-contract-lab',
    name: 'Nexus Data Contract Lab',
    buyer: 'Data platform, analytics engineering, and operations BI teams',
    paidMotion: 'Connector pack, data-quality migration sprint, or audit/report export bundle',
    tagline: 'Governed NL-to-SQL, lakehouse contracts, Korean document automation, and report-ready public-data mapping.',
    primaryRepos: ['Nexus-Hive', 'lakehouse-contract-lab', 'secure-xl2hwp-local'],
    supportRepos: ['districtpilot-ai', 'snowflake-demo-pack', 'fde-engagement-playbook'],
    proofSignal: 'Contracts · public data · document automation',
    ctaUrl: 'https://github.com/KIM3310/KIM3310/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+governed+data+automation',
  },
  {
    id: 'smallbiz-checkout-ops',
    name: 'SmallBiz Checkout Ops Pilot',
    buyer: 'Owner-operated shops, agency ops leads, and Korean SMB support teams',
    paidMotion: 'Single-vertical setup package with approval-safe inbox, public-data enrichment, and checkout readiness',
    tagline: 'Approval-first support console with Korean public API and Toss/PortOne/Stripe readiness boundaries.',
    primaryRepos: ['smallbiz-ops-copilot'],
    supportRepos: ['regulated-case-workbench', 'Upstage-DocuAgent', 'memory-test-master-change-gate'],
    proofSignal: 'Approval inbox · public APIs · checkout readiness',
    ctaUrl: 'https://github.com/KIM3310/KIM3310/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+small+business+ops+pilot',
  },
  {
    id: 'industrial-validation-pack',
    name: 'Industrial Validation Pack',
    buyer: 'Manufacturing operations and industrial AI validation teams',
    paidMotion: 'Synthetic control-tower workshop, private dataset evaluation, or model-card/report package',
    tagline: 'Factory control-tower proof, inspection model cards, and guarded validation workflows without safety guarantees.',
    primaryRepos: ['fab-ops-yield-control-tower', 'weld-defect-vision'],
    supportRepos: ['memory-test-master-change-gate', 'dv-regression-lab'],
    proofSignal: 'Control tower · model cards · validation reports',
    ctaUrl: 'https://github.com/KIM3310/KIM3310/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+industrial+validation',
  },
] as const;
