export const SELECTED_WORK = [
  {
    repo: 'AegisOps', title: 'AegisOps', discipline: "01 / End-to-end AI software",
    problem: 'Turn incident logs and screenshots into a report another operator can act on.',
    decision: 'Typed reports, server-side providers, deterministic replays, and session recovery.',
    command: 'npm ci && npm run verify',
    source: 'server/lib/sessionStore.ts', proof: '__tests__/session-store.test.ts',
    boundary: 'The public demo uses synthetic incidents. Provider-backed analysis runs through the local API.',
  },
  {
    repo: 'idlemesh', title: 'IdleMesh', discipline: "02 / Scheduling & recovery",
    problem: 'Recover interrupted compute shards without accepting results from an obsolete attempt.',
    decision: 'SQLite transactions, a fresh token per lease, and capacity derived from live work.',
    command: 'npm ci && npm run verify && npm run proof:recovery',
    source: 'src/db.ts', proof: 'tests/lease-fencing.test.ts',
    boundary: 'Private source. Local HTTP recovery uses real CPU work with an injected failure; measured local concurrency and recovery are documented. Multi-device performance is unmeasured.',
  },
  {
    repo: 'memoryflow-lab', title: 'MemoryFlow Lab', discipline: "03 / Quantitative systems reasoning",
    problem: 'Compare KV-cache placement when a workload exceeds the modeled memory budget.',
    decision: 'Page-aware capacity constraints, latency/energy trade-offs, and reproducible sensitivity analysis.',
    command: 'make install && make verify',
    source: 'src/memoryflow/simulator.py', proof: 'tests/test_simulator.py',
    boundary: 'HBM/CXL results are analytical estimates. Committed MPS measurements cover narrower copy and attention experiments.',
  },
  {
    repo: 'Nexus-Hive', title: 'Nexus-Hive', discipline: "04 / Controlled data execution",
    problem: 'Convert a natural-language question into SQL without skipping the execution policy.',
    decision: 'Parse SQL structure; inspect columns and statements; stop denied and review-required queries before execution.',
    command: 'make install && make verify',
    source: 'policy/engine.py', proof: 'tests/test_sql_policy_boundaries.py',
    boundary: 'SQLite is the local demo. SQL policy is an application gate; database permissions remain necessary.',
  },
  {
    repo: 'stage-pilot', title: 'StagePilot', discipline: "05 / Runtime & experiment design",
    problem: 'Recover malformed tool calls and show exactly which cases still fail.',
    decision: 'Bounded retries and a case-by-case benchmark make recovery behavior inspectable.',
    command: 'pnpm install --frozen-lockfile && pnpm verify',
    source: 'src/stagepilot/benchmark.ts', proof: 'tests/stagepilot-benchmark.test.ts',
    boundary: 'An attributed extension of upstream Apache-2.0 code. The benchmark uses synthetic inputs and prewritten retry responses.',
  },
  {
    repo: "twincity-ui",
    title: "TwinCity UI",
    discipline: "06 / Spatial interaction & live feeds",
    problem: "Map mixed event feeds into an operator console that survives connection failures.",
    decision: "Calibrated coordinates, one active transport, stale-response fencing, and on-demand 3D.",
    command: "npm ci && npm run verify",
    source: "src/lib/liveFeed.ts",
    proof: "tests/liveFeedHttp.test.ts",
    boundary: "The interactive preview uses synthetic events and checked-in spatial assets. Local HTTP recovery is tested; deployed sensor integrations are unverified.",
  },
  {
    repo: "lakehouse-contract-lab",
    title: "Lakehouse Contract Lab",
    discipline: "07 / Data pipelines & contracts",
    problem: "Turn raw orders into trusted KPI tables while retaining rejected rows and reproducible output.",
    decision: "Actual Spark/Delta writes, explicit quality rules, UTC serialization, and independent readback.",
    command: "make install && .venv/bin/python -m scripts.verify_spark_runtime",
    source: "scripts/build_lakehouse_artifacts.py",
    proof: "scripts/verify_spark_runtime.py",
    boundary: "Real Spark 3.5.9 and Delta 3.3.3 execution on a synthetic 12-row fixture: 8 accepted records and 5 KPI rows. Not a scale or cloud-export benchmark.",
  },
  {
    repo: "SteadyTap",
    title: "SteadyTap",
    discipline: "08 / Native mobile interaction",
    problem: "Adapt touch controls from tap and drag measurements, then compare practice results.",
    decision: "One shared calibration core, invalid-sample rejection, local-only release policy, and native gesture tests.",
    command: "./scripts/verify_cli.sh && make verify-app-store",
    source: "Core/CalibrationEngine.swift",
    proof: "UITests/CalibrationFlowTests.swift",
    boundary: "Native release build and simulator tap/drag flow passed; the observed run and launch screen are linked. Physical-device performance, clinical benefit and App Store publication are not claimed.",
  },
  {
    repo: 'memory-test-master-change-gate', title: 'Memory Change Gate', discipline: "09 / Change integrity",
    problem: 'Trace a master-data change through dependencies, approvals, release conditions, and rollback.',
    decision: 'Bind decisions to exact source snapshots and reconstruct domain results when verifying an export.',
    command: 'make install && make verify',
    source: 'app/core/exports.py', proof: 'tests/test_bundle_resource_limits.py',
    boundary: 'Private source. All master data and approvals are synthetic; unsigned bundles establish consistency, not publisher identity.',
  },
  {
    repo: 'secure-xl2hwp-local', title: 'Secure XL2HWP', discipline: "10 / Practical document automation",
    problem: 'Clean spreadsheets and produce traceable Hancom template payloads on a local machine.',
    decision: 'Schema-driven cleanup, template checks, signed audit bundles, and distinct artifacts for every export.',
    command: 'make install && make verify',
    source: 'app/services/export_service.py', proof: 'tests/test_pipeline_service.py',
    boundary: 'Cross-platform checks cover normalized files and template payloads. Native HWP output needs Windows and Hancom.',
  },
  {
    repo: 'tool-call-finetune-lab', title: 'Tool-Call Fine-Tune Lab', discipline: "11 / Evaluation & data integrity",
    problem: 'Build a tool-call evaluation that cannot benefit from future answers or matching requests across data splits.',
    decision: 'Context isolation, complete JSON comparison, grouped splits, and reproducible evaluator contracts.',
    command: 'make install && make verify && make proof',
    source: 'src/tool_call_finetune_lab/eval/bfcl_runner.py', proof: 'tests/test_evaluation_integrity.py',
    boundary: 'CPU checks use synthetic cases. GPU training and model-quality gains are unverified; this is not an official BFCL score.',
  },
  {
    repo: "llm-onprem-deployment-kit",
    title: "LLM On-Prem Deployment Kit",
    discipline: "12 / Infrastructure & deployment",
    problem: "Make a private LLM stack inspectable from Terraform configuration through TLS and secret wiring.",
    decision: "Provider locks, Helm contracts, HTTPS routing and a real Kubernetes deployment smoke.",
    command: "make verify && make validate",
    source: "helm/llm-stack/templates/gateway-dynamic-configmap.yaml",
    proof: "tests/cluster-smoke.sh",
    boundary: "Eight Terraform directories validate. Kubernetes smoke uses real Traefik/TLS and synthetic inference; GPU inference and customer cloud deployment remain unverified.",
  },
  {
    repo: "kbbq-idle-unity",
    title: "KBBQ Idle Unity",
    discipline: "13 / Game systems & economy",
    problem: "Keep idle-game rewards bounded across clock changes, offline caps and invalid numeric values.",
    decision: "Unity and .NET compile one reward formula; historical WebGL assets carry checksums and an original build date.",
    command: "dotnet test sim/KbbqIdle.Sim.Tests && make verify",
    source: "Assets/Scripts/Systems/OfflineEarningsMath.cs",
    proof: "sim/KbbqIdle.Sim.Tests/MathTests.cs",
    boundary: "12 .NET and 10 backend tests pass. The playable WebGL build dates to 2026-02-20 and does not contain a verified rebuild of the new source.",
  },
] as const;

export const selectedWorkFor = (repo: string) => SELECTED_WORK.find(work => work.repo === repo);
