export const SERVICE_OFFERS = [
  {
    "repo": "AegisOps",
    "name": "AegisOps",
    "canonicalUrl": "https://aegisops-ai-incident-doctor.pages.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=AegisOps%20private%20workspace&body=I%20am%20interested%20in%20team%20workspace%20for%20incident%20packs%2C%20replay%20history%2C%20export%20branding%2C%20and%20private%20provider%20keys%20for%20AegisOps.",
    "repositoryUrl": "https://github.com/KIM3310/AegisOps",
    "architectureUrl": "https://github.com/KIM3310/AegisOps/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/AegisOps/blob/main/docs/revenue-architecture.md",
    "offer": "incident replay copilot with evidence capture, runbook drafting, and post-incident summary export",
    "freeEntry": "public replay demo plus downloadable incident-readout template",
    "paidSku": "team workspace for incident packs, replay history, export branding, and private provider keys",
    "primaryQuery": "AegisOps incident replay copilot",
    "category": "BusinessApplication"
  },
  {
    "repo": "KIM3310",
    "name": "KIM3310",
    "canonicalUrl": "https://kim3310.github.io/doeon-kim-portfolio/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=KIM3310%20private%20workspace&body=I%20am%20interested%20in%20paid%20implementation%20package%2C%20architecture%20adaptation%20package%2C%20or%20template%20bundle%20attached%20to%20selected%20systems%20for%20KIM3310.",
    "repositoryUrl": "https://github.com/KIM3310/KIM3310",
    "architectureUrl": "https://github.com/KIM3310/KIM3310/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/KIM3310/blob/main/docs/revenue-architecture.md",
    "offer": "systems catalog that routes visitors to runnable demos, architecture packs, and productized service templates",
    "freeEntry": "public architecture index with free system diagrams and deployment notes",
    "paidSku": "paid implementation package, architecture adaptation package, or template bundle attached to selected systems",
    "primaryQuery": "KIM3310 systems catalog routes",
    "category": "DeveloperApplication"
  },
  {
    "repo": "Nexus-Hive",
    "name": "Nexus Hive",
    "canonicalUrl": "https://nexus-hive.pages.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Nexus%20Hive%20private%20workspace&body=I%20am%20interested%20in%20paid%20private%20connector%20pack%20for%20Snowflake%2FDatabricks%2FPostgres%20plus%20audit%20export%20bundle%20for%20Nexus%20Hive.",
    "repositoryUrl": "https://github.com/KIM3310/Nexus-Hive",
    "architectureUrl": "https://github.com/KIM3310/Nexus-Hive/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/Nexus-Hive/blob/main/docs/revenue-architecture.md",
    "offer": "governed query gateway with policy checks, semantic metadata, audit logs, and warehouse adapter contracts",
    "freeEntry": "public governed analytics demo over synthetic sales data",
    "paidSku": "paid private connector pack for Snowflake/Databricks/Postgres plus audit export bundle",
    "primaryQuery": "Nexus Hive governed query gateway",
    "category": "BusinessApplication"
  },
  {
    "repo": "SteadyTap",
    "name": "SteadyTap",
    "canonicalUrl": "https://steadytap.pages.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=SteadyTap%20private%20workspace&body=I%20am%20interested%20in%20premium%20progress%20history%2C%20organization%20dashboard%2C%20and%20private%20calibration%20templates%20for%20SteadyTap.",
    "repositoryUrl": "https://github.com/KIM3310/SteadyTap",
    "architectureUrl": "https://github.com/KIM3310/SteadyTap/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/SteadyTap/blob/main/docs/revenue-architecture.md",
    "offer": "calibration and adaptive touch challenge toolkit with coach planning and cloud sync option",
    "freeEntry": "free local-first mobile demo and static explainer",
    "paidSku": "premium progress history, organization dashboard, and private calibration templates",
    "primaryQuery": "SteadyTap calibration adaptive touch",
    "category": "HealthApplication"
  },
  {
    "repo": "agent-orchestration-benchmark",
    "name": "Agent Orchestration Benchmark",
    "canonicalUrl": "https://kim3310.github.io/agent-orchestration-benchmark/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Agent%20Orchestration%20Benchmark%20private%20workspace&body=I%20am%20interested%20in%20paid%20benchmark%20report%20pack%2C%20private%20scenario%20suite%2C%20and%20recurring%20provider%20regression%20dashboard%20for%20Agent%20Orchestration%20Benchmark.",
    "repositoryUrl": "https://github.com/KIM3310/agent-orchestration-benchmark",
    "architectureUrl": "https://github.com/KIM3310/agent-orchestration-benchmark/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/agent-orchestration-benchmark/blob/main/docs/revenue-architecture.md",
    "offer": "benchmark harness and report generator for agent orchestration reliability",
    "freeEntry": "free benchmark methodology and sample leaderboard",
    "paidSku": "paid benchmark report pack, private scenario suite, and recurring provider regression dashboard",
    "primaryQuery": "Agent Orchestration Benchmark harness generator reliability",
    "category": "DeveloperApplication"
  },
  {
    "repo": "agent-runtime-go",
    "name": "Agent Runtime Go",
    "canonicalUrl": "https://kim3310.github.io/agent-runtime-go/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Agent%20Runtime%20Go%20private%20workspace&body=I%20am%20interested%20in%20hosted%20trace%20console%2C%20team%20policy%20registry%2C%20and%20enterprise%20adapter%20support%20for%20Agent%20Runtime%20Go.",
    "repositoryUrl": "https://github.com/KIM3310/agent-runtime-go",
    "architectureUrl": "https://github.com/KIM3310/agent-runtime-go/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/agent-runtime-go/blob/main/docs/revenue-architecture.md",
    "offer": "small Go runtime for retries, validation, provider adapters, and inspectable execution traces",
    "freeEntry": "open-source runtime plus quickstart examples",
    "paidSku": "hosted trace console, team policy registry, and enterprise adapter support",
    "primaryQuery": "Agent Runtime Go small retries validation",
    "category": "DeveloperApplication"
  },
  {
    "repo": "ai-agent-production-lab",
    "name": "AI Agent Production Lab",
    "canonicalUrl": "https://kim3310.github.io/ai-agent-production-lab/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=AI%20Agent%20Production%20Lab%20private%20workspace&body=I%20am%20interested%20in%20paid%20readiness%20report%2C%20hardened%20template%20pack%2C%20and%20hosted%20scorecard%20dashboard%20for%20AI%20Agent%20Production%20Lab.",
    "repositoryUrl": "https://github.com/KIM3310/ai-agent-production-lab",
    "architectureUrl": "https://github.com/KIM3310/ai-agent-production-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/ai-agent-production-lab/blob/main/docs/revenue-architecture.md",
    "offer": "production-readiness lab with guardrails, tracing, deployment checklist, and report artifacts",
    "freeEntry": "free production checklist and sample report",
    "paidSku": "paid readiness report, hardened template pack, and hosted scorecard dashboard",
    "primaryQuery": "AI Agent Production Lab production-readiness guardrails tracing",
    "category": "DeveloperApplication"
  },
  {
    "repo": "ai-security-redteam-lab",
    "name": "AI Security Redteam Lab",
    "canonicalUrl": "https://kim3310.github.io/ai-security-redteam-lab/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=AI%20Security%20Redteam%20Lab%20private%20workspace&body=I%20am%20interested%20in%20private%20red-team%20scenario%20suite%20and%20recurring%20scan%20report%20dashboard%20for%20AI%20Security%20Redteam%20Lab.",
    "repositoryUrl": "https://github.com/KIM3310/ai-security-redteam-lab",
    "architectureUrl": "https://github.com/KIM3310/ai-security-redteam-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/ai-security-redteam-lab/blob/main/docs/revenue-architecture.md",
    "offer": "red-team scenario runner with risk taxonomy, prompt attack cases, and mitigation reports",
    "freeEntry": "public sample attack catalog and static report",
    "paidSku": "private red-team scenario suite and recurring scan report dashboard",
    "primaryQuery": "AI Security Redteam Lab red-team scenario runner",
    "category": "SecurityApplication"
  },
  {
    "repo": "aix-pilot",
    "name": "AIX Pilot",
    "canonicalUrl": "https://aix-pilot.pages.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=AIX%20Pilot%20private%20workspace&body=I%20am%20interested%20in%20paid%20pilot%20workspace%20with%20private%20docs%2C%20provider%20keys%2C%20KPI%20dashboards%2C%20and%20exportable%20business%20case%20for%20AIX%20Pilot.",
    "repositoryUrl": "https://github.com/KIM3310/aix-pilot",
    "architectureUrl": "https://github.com/KIM3310/aix-pilot/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/aix-pilot/blob/main/docs/revenue-architecture.md",
    "offer": "enterprise GenAI pilot console with RAG fixtures, DLP masking, KPI views, and evaluation flows",
    "freeEntry": "public Cloudflare Pages demo with synthetic fixtures",
    "paidSku": "paid pilot workspace with private docs, provider keys, KPI dashboards, and exportable business case",
    "primaryQuery": "AIX Pilot enterprise GenAI console",
    "category": "BusinessApplication"
  },
  {
    "repo": "beaver-study-orchestrator",
    "name": "Beaver Study Orchestrator",
    "canonicalUrl": "https://kim3310.github.io/beaver-study-orchestrator/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Beaver%20Study%20Orchestrator%20private%20workspace&body=I%20am%20interested%20in%20premium%20study%20history%2C%20cohort%20dashboard%2C%20and%20exportable%20progress%20report%20for%20Beaver%20Study%20Orchestrator.",
    "repositoryUrl": "https://github.com/KIM3310/beaver-study-orchestrator",
    "architectureUrl": "https://github.com/KIM3310/beaver-study-orchestrator/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/beaver-study-orchestrator/blob/main/docs/revenue-architecture.md",
    "offer": "study orchestration board with planning, outcomes, history, and adaptive next steps",
    "freeEntry": "free local study planner and public demo",
    "paidSku": "premium study history, cohort dashboard, and exportable progress report",
    "primaryQuery": "Beaver Study Orchestrator orchestration board planning",
    "category": "EducationalApplication"
  },
  {
    "repo": "districtpilot-ai",
    "name": "Districtpilot AI",
    "canonicalUrl": "https://kim3310.github.io/districtpilot-ai/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Districtpilot%20AI%20private%20workspace&body=I%20am%20interested%20in%20paid%20readiness%20report%2C%20data%20connector%20pack%2C%20and%20private%20planning%20workspace%20for%20Districtpilot%20AI.",
    "repositoryUrl": "https://github.com/KIM3310/districtpilot-ai",
    "architectureUrl": "https://github.com/KIM3310/districtpilot-ai/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/districtpilot-ai/blob/main/docs/revenue-architecture.md",
    "offer": "district operations planning and public API readiness explorer",
    "freeEntry": "public static district planning demo with architecture notes",
    "paidSku": "paid readiness report, data connector pack, and private planning workspace",
    "primaryQuery": "Districtpilot AI district operations planning",
    "category": "BusinessApplication"
  },
  {
    "repo": "doeon-kim-portfolio",
    "name": "KIM3310 Systems Gallery",
    "canonicalUrl": "https://kim3310.github.io/doeon-kim-portfolio/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=KIM3310%20Systems%20Gallery%20private%20workspace&body=I%20am%20interested%20in%20paid%20architecture%20pack%20bundle%2C%20implementation%20sprint%2C%20or%20private%20adaptation%20of%20a%20repo%20for%20KIM3310%20Systems%20Gallery.",
    "repositoryUrl": "https://github.com/KIM3310/doeon-kim-portfolio",
    "architectureUrl": "https://github.com/KIM3310/doeon-kim-portfolio/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/doeon-kim-portfolio/blob/main/docs/revenue-architecture.md",
    "offer": "product storefront for architecture packs, demos, and implementation-ready systems",
    "freeEntry": "free systems gallery with live demos and architecture links",
    "paidSku": "paid architecture pack bundle, implementation sprint, or private adaptation of a repo",
    "primaryQuery": "KIM3310 Systems Gallery product storefront architecture",
    "category": "DeveloperApplication"
  },
  {
    "repo": "dream-interpretation-pages",
    "name": "Dream Interpretation Pages",
    "canonicalUrl": "https://kim3310.github.io/dream-interpretation-pages/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Dream%20Interpretation%20Pages%20private%20workspace&body=I%20am%20interested%20in%20premium%20saved%20journal%2C%20long-form%20reports%2C%20themes%2C%20and%20export%20packs%20for%20Dream%20Interpretation%20Pages.",
    "repositoryUrl": "https://github.com/KIM3310/dream-interpretation-pages",
    "architectureUrl": "https://github.com/KIM3310/dream-interpretation-pages/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/dream-interpretation-pages/blob/main/docs/revenue-architecture.md",
    "offer": "dream interpretation pages with private journaling, symbolic prompts, and shareable report cards",
    "freeEntry": "free interpretation page with limited daily reports",
    "paidSku": "premium saved journal, long-form reports, themes, and export packs",
    "primaryQuery": "Dream Interpretation Pages journaling symbolic prompts",
    "category": "LifestyleApplication"
  },
  {
    "repo": "enterprise-llm-adoption-kit",
    "name": "Enterprise LLM Adoption Kit",
    "canonicalUrl": "https://enterprise-llm-kit.pages.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Enterprise%20LLM%20Adoption%20Kit%20private%20workspace&body=I%20am%20interested%20in%20paid%20workshop%20pack%2C%20private%20control%20tower%20deployment%2C%20and%20governance%20evidence%20bundle%20for%20Enterprise%20LLM%20Adoption%20Kit.",
    "repositoryUrl": "https://github.com/KIM3310/enterprise-llm-adoption-kit",
    "architectureUrl": "https://github.com/KIM3310/enterprise-llm-adoption-kit/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/enterprise-llm-adoption-kit/blob/main/docs/revenue-architecture.md",
    "offer": "adoption kit with governance controls, workshop assets, service briefs, evals, and control tower surfaces",
    "freeEntry": "public templates, service brief samples, and architecture docs",
    "paidSku": "paid workshop pack, private control tower deployment, and governance evidence bundle",
    "primaryQuery": "Enterprise LLM Adoption Kit governance controls workshop",
    "category": "BusinessApplication"
  },
  {
    "repo": "fab-ops-yield-control-tower",
    "name": "Fab Ops Yield Control Tower",
    "canonicalUrl": "https://fab-ops-yield-control-tower.pages.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Fab%20Ops%20Yield%20Control%20Tower%20private%20workspace&body=I%20am%20interested%20in%20paid%20factory%20pilot%20workspace%20with%20private%20connectors%20and%20shift%20report%20export%20for%20Fab%20Ops%20Yield%20Control%20Tower.",
    "repositoryUrl": "https://github.com/KIM3310/fab-ops-yield-control-tower",
    "architectureUrl": "https://github.com/KIM3310/fab-ops-yield-control-tower/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/fab-ops-yield-control-tower/blob/main/docs/revenue-architecture.md",
    "offer": "yield control tower with alarm triage, lot risk, release gates, and shift handoff",
    "freeEntry": "public synthetic fab demo and operating model",
    "paidSku": "paid factory pilot workspace with private connectors and shift report export",
    "primaryQuery": "Fab Ops Yield Control Tower alarm triage lot",
    "category": "BusinessApplication"
  },
  {
    "repo": "kbbq-idle-unity",
    "name": "KBBQ Idle Unity",
    "canonicalUrl": "https://kbbq-idle-unity.pages.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=KBBQ%20Idle%20Unity%20private%20workspace&body=I%20am%20interested%20in%20cosmetic%20packs%2C%20ad-free%20mode%2C%20event%20boosts%2C%20and%20supporter%20bundle%20for%20KBBQ%20Idle%20Unity.",
    "repositoryUrl": "https://github.com/KIM3310/kbbq-idle-unity",
    "architectureUrl": "https://github.com/KIM3310/kbbq-idle-unity/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/kbbq-idle-unity/blob/main/docs/revenue-architecture.md",
    "offer": "Korean BBQ idle game with progression, leaderboard, events, and collectible content",
    "freeEntry": "free WebGL build on Pages/itch.io",
    "paidSku": "cosmetic packs, ad-free mode, event boosts, and supporter bundle",
    "primaryQuery": "KBBQ Idle Unity Korean BBQ game",
    "category": "GameApplication"
  },
  {
    "repo": "lakehouse-contract-lab",
    "name": "Lakehouse Contract Lab",
    "canonicalUrl": "https://kim3310.github.io/lakehouse-contract-lab/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Lakehouse%20Contract%20Lab%20private%20workspace&body=I%20am%20interested%20in%20paid%20connector%20templates%2C%20contract%20migration%20pack%2C%20and%20recurring%20data%20quality%20report%20for%20Lakehouse%20Contract%20Lab.",
    "repositoryUrl": "https://github.com/KIM3310/lakehouse-contract-lab",
    "architectureUrl": "https://github.com/KIM3310/lakehouse-contract-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/lakehouse-contract-lab/blob/main/docs/revenue-architecture.md",
    "offer": "lakehouse contract compiler, quality gate, artifact builder, and export adapter lab",
    "freeEntry": "free synthetic pipeline and contract examples",
    "paidSku": "paid connector templates, contract migration pack, and recurring data quality report",
    "primaryQuery": "Lakehouse Contract Lab compiler quality gate",
    "category": "DeveloperApplication"
  },
  {
    "repo": "llm-onprem-deployment-kit",
    "name": "LLM On-Prem Deployment Kit",
    "canonicalUrl": "https://kim3310.github.io/llm-onprem-deployment-kit/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=LLM%20On-Prem%20Deployment%20Kit%20private%20workspace&body=I%20am%20interested%20in%20paid%20private%20deployment%20support%2C%20hardened%20values%20pack%2C%20and%20upgrade%20runbook%20subscription%20for%20LLM%20On-Prem%20Deployment%20Kit.",
    "repositoryUrl": "https://github.com/KIM3310/llm-onprem-deployment-kit",
    "architectureUrl": "https://github.com/KIM3310/llm-onprem-deployment-kit/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/llm-onprem-deployment-kit/blob/main/docs/revenue-architecture.md",
    "offer": "deployment kit for Kubernetes, Helm, Terraform, observability, and security controls",
    "freeEntry": "free reference architecture and Helm/Terraform starter kit",
    "paidSku": "paid private deployment support, hardened values pack, and upgrade runbook subscription",
    "primaryQuery": "LLM On-Prem Deployment Kit Kubernetes Helm Terraform",
    "category": "DeveloperApplication"
  },
  {
    "repo": "multi-cli-pilot",
    "name": "Multi-CLI Pilot",
    "canonicalUrl": "https://kim3310.github.io/multi-cli-pilot/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Multi-CLI%20Pilot%20private%20workspace&body=I%20am%20interested%20in%20team%20workflow%20library%2C%20hosted%20run%20history%2C%20and%20provider%20cost%20dashboard%20for%20Multi-CLI%20Pilot.",
    "repositoryUrl": "https://github.com/KIM3310/multi-cli-pilot",
    "architectureUrl": "https://github.com/KIM3310/multi-cli-pilot/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/multi-cli-pilot/blob/main/docs/revenue-architecture.md",
    "offer": "multi-CLI orchestration runner with reproducible task routes and provider abstraction",
    "freeEntry": "free CLI recipes and demo tasks",
    "paidSku": "team workflow library, hosted run history, and provider cost dashboard",
    "primaryQuery": "Multi-CLI Pilot orchestration runner reproducible",
    "category": "DeveloperApplication"
  },
  {
    "repo": "nw-service-assurance-workbench",
    "name": "NW Service Assurance Workbench",
    "canonicalUrl": "https://nw-service-assurance-workbench.ehdjs1351.workers.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=NW%20Service%20Assurance%20Workbench%20private%20workspace&body=I%20am%20interested%20in%20paid%20workspace%20for%20service%20maps%2C%20private%20incident%20history%2C%20and%20recurring%20SLA%20reports%20for%20NW%20Service%20Assurance%20Workbench.",
    "repositoryUrl": "https://github.com/KIM3310/nw-service-assurance-workbench",
    "architectureUrl": "https://github.com/KIM3310/nw-service-assurance-workbench/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/nw-service-assurance-workbench/blob/main/docs/revenue-architecture.md",
    "offer": "network service assurance workbench with SLA signals, service paths, and incident handoff",
    "freeEntry": "public synthetic network operations demo",
    "paidSku": "paid workspace for service maps, private incident history, and recurring SLA reports",
    "primaryQuery": "NW Service Assurance Workbench network SLA signals",
    "category": "BusinessApplication"
  },
  {
    "repo": "quantum-workbench",
    "name": "Quantum Workbench",
    "canonicalUrl": "https://kim3310.github.io/quantum-workbench/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Quantum%20Workbench%20private%20workspace&body=I%20am%20interested%20in%20paid%20lab%20workspace%2C%20course%20bundle%2C%20and%20provider-cost%20planning%20reports%20for%20Quantum%20Workbench.",
    "repositoryUrl": "https://github.com/KIM3310/quantum-workbench",
    "architectureUrl": "https://github.com/KIM3310/quantum-workbench/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/quantum-workbench/blob/main/docs/revenue-architecture.md",
    "offer": "quantum experiment workbench with provider adapters, job inspection, and educational reports",
    "freeEntry": "free simulator-first demo and static architecture page",
    "paidSku": "paid lab workspace, course bundle, and provider-cost planning reports",
    "primaryQuery": "Quantum Workbench experiment provider adapters",
    "category": "EducationalApplication"
  },
  {
    "repo": "retina-scan-ai",
    "name": "Retina Scan AI",
    "canonicalUrl": "https://kim3310.github.io/retina-scan-ai/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Retina%20Scan%20AI%20private%20workspace&body=I%20am%20interested%20in%20paid%20education%20workspace%2C%20research%20report%20pack%2C%20and%20private%20dataset%20evaluation%20support%20for%20Retina%20Scan%20AI.",
    "repositoryUrl": "https://github.com/KIM3310/retina-scan-ai",
    "architectureUrl": "https://github.com/KIM3310/retina-scan-ai/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/retina-scan-ai/blob/main/docs/revenue-architecture.md",
    "offer": "retinal classification research demo with Grad-CAM style explainability and compliance notes",
    "freeEntry": "free static research demo with non-diagnostic framing",
    "paidSku": "paid education workspace, research report pack, and private dataset evaluation support",
    "primaryQuery": "Retina Scan AI retinal classification research",
    "category": "EducationalApplication"
  },
  {
    "repo": "secure-xl2hwp-local",
    "name": "Secure XL2HWP Local",
    "canonicalUrl": "https://secure-xl2hwp-local.pages.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Secure%20XL2HWP%20Local%20private%20workspace&body=I%20am%20interested%20in%20paid%20local%20license%2C%20deployment%20package%2C%20and%20template%20adaptation%20support%20for%20Secure%20XL2HWP%20Local.",
    "repositoryUrl": "https://github.com/KIM3310/secure-xl2hwp-local",
    "architectureUrl": "https://github.com/KIM3310/secure-xl2hwp-local/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/secure-xl2hwp-local/blob/main/docs/revenue-architecture.md",
    "offer": "local-only spreadsheet cleanup and Hancom handoff workflow with signed audit/export evidence",
    "freeEntry": "public architecture page that explains trust boundary and handoff path",
    "paidSku": "paid local license, deployment package, and template adaptation support",
    "primaryQuery": "Secure XL2HWP Local local-only spreadsheet cleanup",
    "category": "BusinessApplication"
  },
  {
    "repo": "security-threat-response-workbench",
    "name": "Security Threat Response Workbench",
    "canonicalUrl": "https://security-threat-response-workbench.ehdjs1351.workers.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Security%20Threat%20Response%20Workbench%20private%20workspace&body=I%20am%20interested%20in%20paid%20private%20scenario%20workspace%20and%20recurring%20threat%20exercise%20report%20for%20Security%20Threat%20Response%20Workbench.",
    "repositoryUrl": "https://github.com/KIM3310/security-threat-response-workbench",
    "architectureUrl": "https://github.com/KIM3310/security-threat-response-workbench/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/security-threat-response-workbench/blob/main/docs/revenue-architecture.md",
    "offer": "threat response workbench with scenario board, runbooks, indicators, and snapshot reports",
    "freeEntry": "public synthetic threat-response demo",
    "paidSku": "paid private scenario workspace and recurring threat exercise report",
    "primaryQuery": "Security Threat Response Workbench scenario board runbooks",
    "category": "SecurityApplication"
  },
  {
    "repo": "stage-pilot",
    "name": "StagePilot",
    "canonicalUrl": "https://stage-pilot.pages.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=StagePilot%20private%20workspace&body=I%20am%20interested%20in%20paid%20hosted%20regression%20workspace%2C%20private%20benchmark%20scenarios%2C%20and%20provider%20routing%20dashboard%20for%20StagePilot.",
    "repositoryUrl": "https://github.com/KIM3310/stage-pilot",
    "architectureUrl": "https://github.com/KIM3310/stage-pilot/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/stage-pilot/blob/main/docs/revenue-architecture.md",
    "offer": "tool-calling reliability gateway with regression tests, provider scorecards, and trace observability",
    "freeEntry": "free public benchmark/demo routes and sample traces",
    "paidSku": "paid hosted regression workspace, private benchmark scenarios, and provider routing dashboard",
    "primaryQuery": "StagePilot tool-calling reliability gateway",
    "category": "DeveloperApplication"
  },
  {
    "repo": "the-savior",
    "name": "The Savior",
    "canonicalUrl": "https://kim3310.github.io/the-savior/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=The%20Savior%20private%20workspace&body=I%20am%20interested%20in%20premium%20theme%20packs%2C%20private%20journal%20export%2C%20and%20supporter%20bundle%20for%20The%20Savior.",
    "repositoryUrl": "https://github.com/KIM3310/the-savior",
    "architectureUrl": "https://github.com/KIM3310/the-savior/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/the-savior/blob/main/docs/revenue-architecture.md",
    "offer": "ambient reflection app with guided prompts, candle visuals, and shareable runtime brief",
    "freeEntry": "free static ritual experience",
    "paidSku": "premium theme packs, private journal export, and supporter bundle",
    "primaryQuery": "The Savior ambient reflection app",
    "category": "LifestyleApplication"
  },
  {
    "repo": "tool-call-finetune-lab",
    "name": "Tool-Call Fine-Tune Lab",
    "canonicalUrl": "https://kim3310.github.io/tool-call-finetune-lab/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Tool-Call%20Fine-Tune%20Lab%20private%20workspace&body=I%20am%20interested%20in%20paid%20dataset%20preparation%20pack%2C%20eval%20report%2C%20and%20private%20fine-tuning%20runbook%20for%20Tool-Call%20Fine-Tune%20Lab.",
    "repositoryUrl": "https://github.com/KIM3310/tool-call-finetune-lab",
    "architectureUrl": "https://github.com/KIM3310/tool-call-finetune-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/tool-call-finetune-lab/blob/main/docs/revenue-architecture.md",
    "offer": "fine-tuning and eval pipeline for tool-call datasets, BFCL-style tests, and serving checks",
    "freeEntry": "free open-source pipeline and sample eval reports",
    "paidSku": "paid dataset preparation pack, eval report, and private fine-tuning runbook",
    "primaryQuery": "Tool-Call Fine-Tune Lab fine-tuning eval pipeline",
    "category": "DeveloperApplication"
  },
  {
    "repo": "twincity-ui",
    "name": "TwinCity UI",
    "canonicalUrl": "https://twincity-ui.pages.dev/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=TwinCity%20UI%20private%20workspace&body=I%20am%20interested%20in%20paid%20workspace%20for%20private%20maps%2C%20event%20ingestion%2C%20and%20monthly%20readiness%20reports%20for%20TwinCity%20UI.",
    "repositoryUrl": "https://github.com/KIM3310/twincity-ui",
    "architectureUrl": "https://github.com/KIM3310/twincity-ui/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/twincity-ui/blob/main/docs/revenue-architecture.md",
    "offer": "digital twin operations console with replay, dispatch, readiness, and report surfaces",
    "freeEntry": "public demo with synthetic city/facility events",
    "paidSku": "paid workspace for private maps, event ingestion, and monthly readiness reports",
    "primaryQuery": "TwinCity UI digital twin operations",
    "category": "BusinessApplication"
  },
  {
    "repo": "weld-defect-vision",
    "name": "Weld Defect Vision",
    "canonicalUrl": "https://kim3310.github.io/weld-defect-vision/",
    "leadCaptureUrl": "mailto:ehdjs1351@gmail.com?subject=Weld%20Defect%20Vision%20private%20workspace&body=I%20am%20interested%20in%20paid%20private%20dataset%20evaluation%2C%20model%20card%2Freport%20pack%2C%20and%20edge%20deployment%20package%20for%20Weld%20Defect%20Vision.",
    "repositoryUrl": "https://github.com/KIM3310/weld-defect-vision",
    "architectureUrl": "https://github.com/KIM3310/weld-defect-vision/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/weld-defect-vision/blob/main/docs/revenue-architecture.md",
    "offer": "weld defect detection demo with dataset validation, model serving, and explainable inspection report",
    "freeEntry": "free static inspection demo and architecture page",
    "paidSku": "paid private dataset evaluation, model card/report pack, and edge deployment package",
    "primaryQuery": "Weld Defect Vision detection dataset validation",
    "category": "BusinessApplication"
  }
] as const;

export type ServiceOffer = (typeof SERVICE_OFFERS)[number];
