export const SERVICE_OFFERS = [
  {
    "repo": "AegisOps",
    "name": "AegisOps",
    "canonicalUrl": "https://aegisops-ai-incident-doctor.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=AegisOps&inquiry=incident-operations-exercise#private-inquiry",
    "laneId": "incident-operations-exercise",
    "repositoryUrl": "https://github.com/KIM3310/AegisOps",
    "architectureUrl": "https://github.com/KIM3310/AegisOps/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/AegisOps/blob/main/docs/revenue-architecture.md",
    "offer": "incident replay copilot with evidence capture, runbook drafting, and post-incident summary export",
    "freeEntry": "public replay demo plus downloadable incident-readout template",
    "paidSku": "team workspace for incident packs, replay history, export branding, and private provider keys",
    "primaryQuery": "AegisOps incident replay copilot",
    "category": "BusinessApplication"
  },
  {
    "repo": "KIM3310",
    "name": "KIM3310",
    "canonicalUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=KIM3310&inquiry=architecture-scope-sprint#private-inquiry",
    "laneId": "architecture-scope-sprint",
    "repositoryUrl": "https://github.com/KIM3310/KIM3310",
    "architectureUrl": "https://github.com/KIM3310/KIM3310/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/KIM3310/blob/main/docs/revenue-architecture.md",
    "offer": "systems catalog that routes visitors to runnable demos, architecture packs, and productized service templates",
    "freeEntry": "public architecture index with free system diagrams and deployment notes",
    "paidSku": "paid implementation package, architecture adaptation package, or template bundle attached to selected systems",
    "primaryQuery": "KIM3310 systems catalog routes",
    "category": "DeveloperApplication"
  },
  {
    "repo": "Nexus-Hive",
    "name": "Nexus Hive",
    "canonicalUrl": "https://nexus-hive.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=Nexus-Hive&inquiry=private-ai-readiness-sprint#private-inquiry",
    "laneId": "private-ai-readiness-sprint",
    "repositoryUrl": "https://github.com/KIM3310/Nexus-Hive",
    "architectureUrl": "https://github.com/KIM3310/Nexus-Hive/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/Nexus-Hive/blob/main/docs/revenue-architecture.md",
    "offer": "governed query gateway with policy checks, semantic metadata, audit logs, and warehouse adapter contracts",
    "freeEntry": "public governed analytics demo over synthetic sales data",
    "paidSku": "quoted private AI readiness sprint for governed analytics connectors and audit export scoping",
    "primaryQuery": "Nexus Hive governed query gateway",
    "category": "BusinessApplication"
  },
  {
    "repo": "SteadyTap",
    "name": "SteadyTap",
    "canonicalUrl": "https://steadytap.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=SteadyTap&inquiry=consumer-prototype-customization#private-inquiry",
    "laneId": "consumer-prototype-customization",
    "repositoryUrl": "https://github.com/KIM3310/SteadyTap",
    "architectureUrl": "https://github.com/KIM3310/SteadyTap/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/SteadyTap/blob/main/docs/revenue-architecture.md",
    "offer": "on-device touch-practice utility and adaptive control prototype",
    "freeEntry": "free local-first mobile demo and static explainer",
    "paidSku": "fixed-scope private prototype customization for one audience-specific workflow",
    "primaryQuery": "SteadyTap calibration adaptive touch",
    "category": "UtilitiesApplication"
  },
  {
    "repo": "Upstage-DocuAgent",
    "name": "DocFlow Agent",
    "canonicalUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=Upstage-DocuAgent#service-offers",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=Upstage-DocuAgent&inquiry=secure-workflow-pilot#private-inquiry",
    "laneId": "secure-workflow-pilot",
    "repositoryUrl": "https://github.com/KIM3310/Upstage-DocuAgent",
    "architectureUrl": "https://github.com/KIM3310/Upstage-DocuAgent/blob/main/docs/service-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/Upstage-DocuAgent/blob/main/docs/REVENUE_READINESS.md",
    "offer": "document-to-learning pipeline that turns uploaded files into grounded extraction, Q&A, and LMS-ready exports",
    "freeEntry": "credential-free demo mode, health endpoints, runtime scorecards, schemas, and architecture notes",
    "paidSku": "paid private evaluation or implementation sprint for document ingestion, grounded Q&A, and LMS export workflow setup",
    "primaryQuery": "DocFlow Agent document to LMS export workflow",
    "category": "EducationalApplication"
  },
  {
    "repo": "agent-orchestration-benchmark",
    "name": "Agent Orchestration Benchmark",
    "canonicalUrl": "https://agent-orchestration-benchmark.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=agent-orchestration-benchmark&inquiry=agent-reliability-audit#private-inquiry",
    "laneId": "agent-reliability-audit",
    "repositoryUrl": "https://github.com/KIM3310/agent-orchestration-benchmark",
    "architectureUrl": "https://github.com/KIM3310/agent-orchestration-benchmark/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/agent-orchestration-benchmark/blob/main/docs/revenue-architecture.md",
    "offer": "benchmark harness and report generator for agent orchestration reliability",
    "freeEntry": "free benchmark methodology and sample leaderboard",
    "paidSku": "paid benchmark report pack, private scenario suite, and recurring provider regression dashboard",
    "primaryQuery": "Agent Orchestration Benchmark harness generator reliability",
    "category": "DeveloperApplication"
  },
  {
    "repo": "agent-runtime-go",
    "name": "Agent Runtime Go",
    "canonicalUrl": "https://agent-runtime-go.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=agent-runtime-go&inquiry=agent-reliability-audit#private-inquiry",
    "laneId": "agent-reliability-audit",
    "repositoryUrl": "https://github.com/KIM3310/agent-runtime-go",
    "architectureUrl": "https://github.com/KIM3310/agent-runtime-go/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/agent-runtime-go/blob/main/docs/revenue-architecture.md",
    "offer": "agent reliability audit for Go agent runtimes, tool-call boundaries, retry behavior, provider adapters, and execution traces",
    "freeEntry": "open-source runtime plus quickstart examples",
    "paidSku": "fixed-scope Agent Reliability Audit",
    "primaryQuery": "Agent Reliability Audit for Go agent runtimes",
    "category": "DeveloperApplication"
  },
  {
    "repo": "ai-agent-production-lab",
    "name": "AI Agent Production Lab",
    "canonicalUrl": "https://ai-agent-production-lab.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=ai-agent-production-lab&inquiry=agent-reliability-audit#private-inquiry",
    "laneId": "agent-reliability-audit",
    "repositoryUrl": "https://github.com/KIM3310/ai-agent-production-lab",
    "architectureUrl": "https://github.com/KIM3310/ai-agent-production-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/ai-agent-production-lab/blob/main/docs/revenue-architecture.md",
    "offer": "agent reliability audit with guardrails, trace review, failure taxonomy, provider scorecard, and remediation plan",
    "freeEntry": "free production checklist and sample report",
    "paidSku": "Agent Reliability Audit fixed-scope private audit from USD 1,500",
    "primaryQuery": "AI Agent Production Lab production-readiness guardrails tracing",
    "category": "DeveloperApplication"
  },
  {
    "repo": "ai-security-redteam-lab",
    "name": "AI Security Redteam Lab",
    "canonicalUrl": "https://ai-security-redteam-lab.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=ai-security-redteam-lab&inquiry=agent-reliability-audit#private-inquiry",
    "laneId": "agent-reliability-audit",
    "repositoryUrl": "https://github.com/KIM3310/ai-security-redteam-lab",
    "architectureUrl": "https://github.com/KIM3310/ai-security-redteam-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/ai-security-redteam-lab/blob/main/docs/revenue-architecture.md",
    "offer": "red-team scenario runner with risk taxonomy, prompt attack cases, and mitigation reports",
    "freeEntry": "public sample attack catalog and static report",
    "paidSku": "private red-team scenario suite and recurring scan report dashboard",
    "primaryQuery": "AI Security Redteam Lab red-team scenario runner",
    "category": "SecurityApplication"
  },
  {
    "repo": "aix-pilot",
    "name": "AIX Pilot",
    "canonicalUrl": "https://aix-pilot.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=aix-pilot&inquiry=private-ai-readiness-sprint#private-inquiry",
    "laneId": "private-ai-readiness-sprint",
    "repositoryUrl": "https://github.com/KIM3310/aix-pilot",
    "architectureUrl": "https://github.com/KIM3310/aix-pilot/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/aix-pilot/blob/main/docs/revenue-architecture.md",
    "offer": "browser-based enterprise AI readiness workbench for local retrieval, cited drafts, PII masking, golden-set evaluation, and pilot reporting",
    "freeEntry": "interactive synthetic-data readiness demo",
    "paidSku": "Private AI Readiness Sprint with a use-case scorecard, data and policy boundaries, an evaluation plan, deployment options, and a go or no-go roadmap",
    "primaryQuery": "enterprise AI readiness assessment RAG evaluation",
    "category": "BusinessApplication"
  },
  {
    "repo": "beaver-study-orchestrator",
    "name": "Beaver Study Orchestrator",
    "canonicalUrl": "https://beaver-study-orchestrator.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=beaver-study-orchestrator&inquiry=consumer-prototype-customization#private-inquiry",
    "laneId": "consumer-prototype-customization",
    "repositoryUrl": "https://github.com/KIM3310/beaver-study-orchestrator",
    "architectureUrl": "https://github.com/KIM3310/beaver-study-orchestrator/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/beaver-study-orchestrator/blob/main/docs/revenue-architecture.md",
    "offer": "study orchestration board with planning, outcomes, and adaptive next steps",
    "freeEntry": "free local study planner and public demo",
    "paidSku": "Consumer Prototype Customization",
    "primaryQuery": "Beaver Study Orchestrator orchestration board planning",
    "category": "EducationalApplication"
  },
  {
    "repo": "districtpilot-ai",
    "name": "Districtpilot AI",
    "canonicalUrl": "https://districtpilot-ai.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=districtpilot-ai&inquiry=private-ai-readiness-sprint#private-inquiry",
    "laneId": "private-ai-readiness-sprint",
    "repositoryUrl": "https://github.com/KIM3310/districtpilot-ai",
    "architectureUrl": "https://github.com/KIM3310/districtpilot-ai/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/districtpilot-ai/blob/main/docs/revenue-architecture.md",
    "offer": "district operations planning and public API readiness explorer",
    "freeEntry": "public static district planning demo with architecture notes",
    "paidSku": "paid readiness report, data connector pack, and private planning workspace",
    "primaryQuery": "Districtpilot AI district operations planning",
    "category": "BusinessApplication"
  },
  {
    "repo": "doeon-kim-portfolio",
    "name": "KIM3310 Systems",
    "canonicalUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=doeon-kim-portfolio&inquiry=architecture-scope-sprint#private-inquiry",
    "laneId": "architecture-scope-sprint",
    "repositoryUrl": "https://github.com/KIM3310/doeon-kim-portfolio",
    "architectureUrl": "https://github.com/KIM3310/doeon-kim-portfolio/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/doeon-kim-portfolio/blob/main/docs/revenue-architecture.md",
    "offer": "evidence-backed operational AI, reliability, incident, workflow, and validation services",
    "freeEntry": "runnable systems, architecture documents, and explicit operating boundaries",
    "paidSku": "Architecture Scope Sprint from USD 900",
    "primaryQuery": "agent reliability and operational AI services",
    "category": "ProfessionalService"
  },
  {
    "repo": "dream-interpretation-pages",
    "name": "달빛해몽소",
    "canonicalUrl": "https://dream-interpretation-pages.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=dream-interpretation-pages&inquiry=consumer-prototype-customization#private-inquiry",
    "laneId": "consumer-prototype-customization",
    "repositoryUrl": "https://github.com/KIM3310/dream-interpretation-pages",
    "architectureUrl": "https://github.com/KIM3310/dream-interpretation-pages/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/dream-interpretation-pages/blob/main/docs/revenue-architecture.md",
    "offer": "AI-assisted dream reflection with browser-local reading history and edited symbol guides",
    "freeEntry": "free dream reflection tool, symbol guide, and browser-local reading history",
    "paidSku": "fixed-scope private product customization for one audience-specific dream reflection workflow",
    "primaryQuery": "AI 꿈 해석 감정 기록",
    "category": "LifestyleApplication"
  },
  {
    "repo": "enterprise-llm-adoption-kit",
    "name": "Enterprise LLM Adoption Kit",
    "canonicalUrl": "https://enterprise-llm-kit.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=enterprise-llm-adoption-kit&inquiry=private-ai-readiness-sprint#private-inquiry",
    "laneId": "private-ai-readiness-sprint",
    "repositoryUrl": "https://github.com/KIM3310/enterprise-llm-adoption-kit",
    "architectureUrl": "https://github.com/KIM3310/enterprise-llm-adoption-kit/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/enterprise-llm-adoption-kit/blob/main/docs/revenue-architecture.md",
    "offer": "adoption kit with governance controls, workshop assets, service briefs, evals, and control tower surfaces",
    "freeEntry": "public templates, service brief samples, and architecture docs",
    "paidSku": "paid workshop pack, private control tower deployment, and governance evidence bundle",
    "primaryQuery": "Enterprise LLM Adoption Kit governance controls workshop",
    "category": "BusinessApplication"
  },
  {
    "repo": "fab-ops-yield-control-tower",
    "name": "Fab Ops Yield Control Tower",
    "canonicalUrl": "https://fab-ops-yield-control-tower.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=fab-ops-yield-control-tower&inquiry=industrial-validation-discovery#private-inquiry",
    "laneId": "industrial-validation-discovery",
    "repositoryUrl": "https://github.com/KIM3310/fab-ops-yield-control-tower",
    "architectureUrl": "https://github.com/KIM3310/fab-ops-yield-control-tower/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/fab-ops-yield-control-tower/blob/main/docs/revenue-architecture.md",
    "offer": "yield control tower with alarm triage, lot risk, release gates, and shift handoff",
    "freeEntry": "public synthetic fab demo and operating model",
    "paidSku": "paid factory pilot workspace with private connectors and shift report export",
    "primaryQuery": "Fab Ops Yield Control Tower alarm triage lot",
    "category": "BusinessApplication"
  },
  {
    "repo": "honeypot",
    "name": "Honeypot Kkuldanji",
    "canonicalUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=honeypot#service-offers",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=honeypot&inquiry=incident-operations-exercise#private-inquiry",
    "laneId": "incident-operations-exercise",
    "repositoryUrl": "https://github.com/KIM3310/honeypot",
    "architectureUrl": "https://github.com/KIM3310/honeypot/blob/main/docs/service-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/honeypot/blob/main/docs/REVENUE_READINESS.md",
    "offer": "synthetic-data document-to-handover workflow evaluation with cited Q&A, completeness gates, and a production security architecture backlog",
    "freeEntry": "credential-free synthetic handover demo, fail-closed security tests, and architecture notes",
    "paidSku": "fixed-scope architecture review and synthetic workflow evaluation; no customer documents or hosted production service",
    "primaryQuery": "Honeypot Kkuldanji document handover assistant",
    "category": "BusinessApplication"
  },
  {
    "repo": "kbbq-idle-unity",
    "name": "KBBQ Idle Unity",
    "canonicalUrl": "https://kbbq-idle-unity.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=kbbq-idle-unity&inquiry=consumer-prototype-customization#private-inquiry",
    "laneId": "consumer-prototype-customization",
    "repositoryUrl": "https://github.com/KIM3310/kbbq-idle-unity",
    "architectureUrl": "https://github.com/KIM3310/kbbq-idle-unity/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/kbbq-idle-unity/blob/main/docs/revenue-architecture.md",
    "offer": "Korean BBQ idle game with progression, leaderboard, events, and collectible content",
    "freeEntry": "free WebGL build on Pages/itch.io",
    "paidSku": "private prototype customization for branded WebGL review builds, content planning, and monetization-readiness handoff",
    "primaryQuery": "KBBQ Idle Unity Korean BBQ game",
    "category": "GameApplication"
  },
  {
    "repo": "lakehouse-contract-lab",
    "name": "Lakehouse Contract Lab",
    "canonicalUrl": "https://lakehouse-contract-lab.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=lakehouse-contract-lab&inquiry=private-ai-readiness-sprint#private-inquiry",
    "laneId": "private-ai-readiness-sprint",
    "repositoryUrl": "https://github.com/KIM3310/lakehouse-contract-lab",
    "architectureUrl": "https://github.com/KIM3310/lakehouse-contract-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/lakehouse-contract-lab/blob/main/docs/revenue-architecture.md",
    "offer": "lakehouse contract compiler, quality gate, artifact builder, and export adapter lab",
    "freeEntry": "free synthetic pipeline and contract examples",
    "paidSku": "quoted private AI readiness sprint for lakehouse contract migration and quality reporting scope",
    "primaryQuery": "Lakehouse Contract Lab compiler quality gate",
    "category": "DeveloperApplication"
  },
  {
    "repo": "llm-onprem-deployment-kit",
    "name": "LLM On-Prem Deployment Kit",
    "canonicalUrl": "https://llm-onprem-deployment-kit.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=llm-onprem-deployment-kit&inquiry=private-ai-readiness-sprint#private-inquiry",
    "laneId": "private-ai-readiness-sprint",
    "repositoryUrl": "https://github.com/KIM3310/llm-onprem-deployment-kit",
    "architectureUrl": "https://github.com/KIM3310/llm-onprem-deployment-kit/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/llm-onprem-deployment-kit/blob/main/docs/revenue-architecture.md",
    "offer": "deployment kit for Kubernetes, Helm, Terraform, observability, and security controls",
    "freeEntry": "free reference architecture and Helm/Terraform starter kit",
    "paidSku": "fixed-scope Private AI Readiness Sprint for one customer-owned deployment decision",
    "primaryQuery": "LLM On-Prem Deployment Kit Kubernetes Helm Terraform",
    "category": "DeveloperApplication"
  },
  {
    "repo": "memory-test-master-change-gate",
    "name": "Memory Test Master Change Impact Gate",
    "canonicalUrl": "https://memory-test-master-change-gate.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=memory-test-master-change-gate&inquiry=industrial-validation-discovery#private-inquiry",
    "laneId": "industrial-validation-discovery",
    "repositoryUrl": "https://github.com/KIM3310/memory-test-master-change-gate",
    "architectureUrl": "https://github.com/KIM3310/memory-test-master-change-gate/blob/main/docs/service-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/memory-test-master-change-gate/blob/main/docs/REVENUE_READINESS.md",
    "offer": "manufacturing change-control gate that dry-runs memory test master data changes before downstream semantic breakage",
    "freeEntry": "synthetic public-lite demo with review pack, rollback plan, and deterministic release-gate evidence",
    "paidSku": "paid private evaluation or implementation sprint for staged master data impact analysis and release-gate evidence",
    "primaryQuery": "Memory Test Master Change Impact Gate release gate",
    "category": "BusinessApplication"
  },
  {
    "repo": "multi-cli-pilot",
    "name": "Multi-CLI Pilot",
    "canonicalUrl": "https://multi-cli-pilot.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=multi-cli-pilot&inquiry=agent-reliability-audit#private-inquiry",
    "laneId": "agent-reliability-audit",
    "repositoryUrl": "https://github.com/KIM3310/multi-cli-pilot",
    "architectureUrl": "https://github.com/KIM3310/multi-cli-pilot/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/multi-cli-pilot/blob/main/docs/revenue-architecture.md",
    "offer": "multi-CLI orchestration runner with reproducible task routes and provider abstraction",
    "freeEntry": "free CLI recipes and demo tasks",
    "paidSku": "team workflow library, hosted run history, and provider cost dashboard",
    "primaryQuery": "Multi-CLI Pilot orchestration runner reproducible",
    "category": "DeveloperApplication"
  },
  {
    "repo": "nw-service-assurance-workbench",
    "name": "NW Service Assurance Workbench",
    "canonicalUrl": "https://nw-service-assurance-workbench.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=nw-service-assurance-workbench&inquiry=incident-operations-exercise#private-inquiry",
    "laneId": "incident-operations-exercise",
    "repositoryUrl": "https://github.com/KIM3310/nw-service-assurance-workbench",
    "architectureUrl": "https://github.com/KIM3310/nw-service-assurance-workbench/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/nw-service-assurance-workbench/blob/main/docs/revenue-architecture.md",
    "offer": "deterministic React and Vite service assurance workbench for carrier incident triage, service paths, runbooks, and operator handoff",
    "freeEntry": "deterministic synthetic carrier-incident demo",
    "paidSku": "facilitated Incident Operations Exercise with a scenario pack, role and handoff map, evidence checklist, and after-action report",
    "primaryQuery": "network service assurance incident response workbench",
    "category": "BusinessApplication"
  },
  {
    "repo": "ops-reliability-workbench",
    "name": "Operations Reliability and Data Governance Workbench",
    "canonicalUrl": "https://ops-reliability-workbench.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=ops-reliability-workbench&inquiry=incident-operations-exercise#private-inquiry",
    "laneId": "incident-operations-exercise",
    "repositoryUrl": "https://github.com/KIM3310/ops-reliability-workbench",
    "architectureUrl": "https://github.com/KIM3310/ops-reliability-workbench/blob/main/docs/service-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/ops-reliability-workbench/blob/main/docs/revenue-architecture.md",
    "offer": "operations reliability desk that packages incident logs, data governance signals, signed bundles, and optional AI assist into a review loop",
    "freeEntry": "credential-free synthetic demo with command center, incident review, release readiness, and signed bundle examples",
    "paidSku": "paid private operations reliability workshop, workbench pilot, or signed evidence bundle implementation",
    "primaryQuery": "Operations Reliability Data Governance Workbench",
    "category": "BusinessApplication"
  },
  {
    "repo": "quantum-workbench",
    "name": "Quantum Workbench",
    "canonicalUrl": "https://quantum-workbench.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=quantum-workbench&inquiry=consumer-prototype-customization#private-inquiry",
    "laneId": "consumer-prototype-customization",
    "repositoryUrl": "https://github.com/KIM3310/quantum-workbench",
    "architectureUrl": "https://github.com/KIM3310/quantum-workbench/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/quantum-workbench/blob/main/docs/revenue-architecture.md",
    "offer": "quantum experiment workbench with provider adapters, job inspection, and educational reports",
    "freeEntry": "free simulator-first demo and static architecture page",
    "paidSku": "private prototype customization for simulator-first lab workspaces, course bundles, and provider-cost planning reports",
    "primaryQuery": "Quantum Workbench experiment provider adapters",
    "category": "EducationalApplication"
  },
  {
    "repo": "regulated-case-workbench",
    "name": "Regulated Case Workbench",
    "canonicalUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=regulated-case-workbench#service-offers",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=regulated-case-workbench&inquiry=secure-workflow-pilot#private-inquiry",
    "laneId": "secure-workflow-pilot",
    "repositoryUrl": "https://github.com/KIM3310/regulated-case-workbench",
    "architectureUrl": "https://github.com/KIM3310/regulated-case-workbench/blob/main/docs/service-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/regulated-case-workbench/blob/main/docs/REVENUE_READINESS.md",
    "offer": "regulated workflow desk for case intake, grounded evidence review, redaction preview, reviewer assignment, policy gating, and signed export proof",
    "freeEntry": "staged public proof with signed export, audit trail, runtime scorecard, and architecture notes",
    "paidSku": "paid private regulated workflow pilot or implementation sprint for approval gates, signed exports, and audit trail design",
    "primaryQuery": "Regulated Case Workbench signed export audit trail",
    "category": "BusinessApplication"
  },
  {
    "repo": "retina-scan-ai",
    "name": "Retina Scan AI",
    "canonicalUrl": "https://retina-scan-ai.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=retina-scan-ai&inquiry=industrial-validation-discovery#private-inquiry",
    "laneId": "industrial-validation-discovery",
    "repositoryUrl": "https://github.com/KIM3310/retina-scan-ai",
    "architectureUrl": "https://github.com/KIM3310/retina-scan-ai/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/retina-scan-ai/blob/main/docs/revenue-architecture.md",
    "offer": "non-clinical synthetic-data retinal classification demo for industrial validation discovery, Grad-CAM review, and model-card scoping",
    "freeEntry": "free synthetic-data research demo with non-diagnostic framing",
    "paidSku": "private industrial validation discovery for data suitability, baseline evaluation, model-card draft, and human-review acceptance criteria",
    "primaryQuery": "Retina Scan AI industrial validation discovery",
    "category": "EducationalApplication"
  },
  {
    "repo": "secure-xl2hwp-local",
    "name": "Secure XL2HWP Local",
    "canonicalUrl": "https://secure-xl2hwp-local.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=secure-xl2hwp-local&inquiry=secure-workflow-pilot#private-inquiry",
    "laneId": "secure-workflow-pilot",
    "repositoryUrl": "https://github.com/KIM3310/secure-xl2hwp-local",
    "architectureUrl": "https://github.com/KIM3310/secure-xl2hwp-local/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/secure-xl2hwp-local/blob/main/docs/revenue-architecture.md",
    "offer": "local-only spreadsheet cleanup and Hancom handoff workflow with signed audit/export evidence",
    "freeEntry": "public architecture page that explains trust boundary and handoff path",
    "paidSku": "fixed-scope customer-owned pilot for one approved Excel-to-Hancom workflow",
    "primaryQuery": "Secure XL2HWP Local local-only spreadsheet cleanup",
    "category": "BusinessApplication"
  },
  {
    "repo": "security-threat-response-workbench",
    "name": "Security Threat Response Workbench",
    "canonicalUrl": "https://security-threat-response-workbench.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=security-threat-response-workbench&inquiry=incident-operations-exercise#private-inquiry",
    "laneId": "incident-operations-exercise",
    "repositoryUrl": "https://github.com/KIM3310/security-threat-response-workbench",
    "architectureUrl": "https://github.com/KIM3310/security-threat-response-workbench/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/security-threat-response-workbench/blob/main/docs/revenue-architecture.md",
    "offer": "threat response workbench with scenario board, runbooks, indicators, and snapshot reports",
    "freeEntry": "public synthetic threat-response demo",
    "paidSku": "Incident Operations Exercise facilitated exercise from USD 1,800",
    "primaryQuery": "Security Threat Response Workbench scenario board runbooks",
    "category": "SecurityApplication"
  },
  {
    "repo": "smallbiz-ops-copilot",
    "name": "SmallBiz Ops Copilot",
    "canonicalUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=smallbiz-ops-copilot#service-offers",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=smallbiz-ops-copilot&inquiry=secure-workflow-pilot#private-inquiry",
    "laneId": "secure-workflow-pilot",
    "repositoryUrl": "https://github.com/KIM3310/smallbiz-ops-copilot",
    "architectureUrl": "https://github.com/KIM3310/smallbiz-ops-copilot/blob/main/docs/service-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/smallbiz-ops-copilot/blob/main/docs/REVENUE_READINESS.md",
    "offer": "Approval-safe support control tower pilot for one signed intake, queue policy, assisted draft workflow, manual approval gate, and auditable webhook handoff",
    "freeEntry": "synthetic local demo, D1 schema, product boundary contract, approval trace, and architecture notes",
    "paidSku": "Secure Workflow Pilot for one support queue with agreed baseline, private data boundary, approval evidence, and deployment runbook",
    "primaryQuery": "approval safe support operations control tower",
    "category": "BusinessApplication"
  },
  {
    "repo": "stage-pilot",
    "name": "StagePilot",
    "canonicalUrl": "https://stage-pilot.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=stage-pilot&inquiry=agent-reliability-audit#private-inquiry",
    "laneId": "agent-reliability-audit",
    "repositoryUrl": "https://github.com/KIM3310/stage-pilot",
    "architectureUrl": "https://github.com/KIM3310/stage-pilot/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/stage-pilot/blob/main/docs/revenue-architecture.md",
    "offer": "tool-calling reliability gateway with regression tests, provider scorecards, and trace observability",
    "freeEntry": "free public benchmark/demo routes and sample traces",
    "paidSku": "paid hosted regression workspace, private benchmark scenarios, and provider routing dashboard",
    "primaryQuery": "StagePilot tool-calling reliability gateway",
    "category": "DeveloperApplication"
  },
  {
    "repo": "the-savior",
    "name": "The Savior",
    "canonicalUrl": "https://the-savior-9z8.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=the-savior&inquiry=consumer-prototype-customization#private-inquiry",
    "laneId": "consumer-prototype-customization",
    "repositoryUrl": "https://github.com/KIM3310/the-savior",
    "architectureUrl": "https://github.com/KIM3310/the-savior/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/the-savior/blob/main/docs/revenue-architecture.md",
    "offer": "ambient reflection app with guided prompts, candle visuals, and shareable runtime brief",
    "freeEntry": "free static ritual experience",
    "paidSku": "premium theme packs, private journal export, and supporter bundle",
    "primaryQuery": "The Savior ambient reflection app",
    "category": "LifestyleApplication"
  },
  {
    "repo": "tool-call-finetune-lab",
    "name": "Tool-Call Fine-Tune Lab",
    "canonicalUrl": "https://tool-call-finetune-lab.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=tool-call-finetune-lab&inquiry=agent-reliability-audit#private-inquiry",
    "laneId": "agent-reliability-audit",
    "repositoryUrl": "https://github.com/KIM3310/tool-call-finetune-lab",
    "architectureUrl": "https://github.com/KIM3310/tool-call-finetune-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/tool-call-finetune-lab/blob/main/docs/revenue-architecture.md",
    "offer": "agent reliability audit for tool-call fine-tuning pipelines, BFCL-style evaluation, schema fidelity, and serving readiness",
    "freeEntry": "free open-source pipeline and sample eval reports",
    "paidSku": "fixed-scope Agent Reliability Audit",
    "primaryQuery": "Agent Reliability Audit for tool-call fine-tuning",
    "category": "DeveloperApplication"
  },
  {
    "repo": "twincity-ui",
    "name": "TwinCity UI",
    "canonicalUrl": "https://twincity-ui.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=twincity-ui&inquiry=architecture-scope-sprint#private-inquiry",
    "laneId": "architecture-scope-sprint",
    "repositoryUrl": "https://github.com/KIM3310/twincity-ui",
    "architectureUrl": "https://github.com/KIM3310/twincity-ui/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/twincity-ui/blob/main/docs/revenue-architecture.md",
    "offer": "digital twin operations console with replay, dispatch, readiness, and report surfaces",
    "freeEntry": "public demo with synthetic city/facility events",
    "paidSku": "Architecture Scope Sprint",
    "primaryQuery": "TwinCity UI digital twin operations",
    "category": "BusinessApplication"
  },
  {
    "repo": "weld-defect-vision",
    "name": "Weld Defect Vision",
    "canonicalUrl": "https://weld-defect-vision.pages.dev/",
    "leadCaptureUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/?offer=weld-defect-vision&inquiry=industrial-validation-discovery#private-inquiry",
    "laneId": "industrial-validation-discovery",
    "repositoryUrl": "https://github.com/KIM3310/weld-defect-vision",
    "architectureUrl": "https://github.com/KIM3310/weld-defect-vision/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/weld-defect-vision/blob/main/docs/revenue-architecture.md",
    "offer": "synthetic-data weld-defect detection demo for industrial validation discovery, data suitability review, and human inspector acceptance criteria",
    "freeEntry": "free synthetic-data inspection demo and architecture page",
    "paidSku": "private industrial validation discovery for data suitability, baseline evaluation, model-card draft, and human-review acceptance criteria",
    "primaryQuery": "Weld Defect Vision industrial validation discovery",
    "category": "BusinessApplication"
  }
] as const;

export type ServiceOffer = (typeof SERVICE_OFFERS)[number];
