export const SERVICE_OFFERS = [
  {
    "repo": "AegisOps",
    "name": "AegisOps",
    "canonicalUrl": "https://aegisops-ai-incident-doctor.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/AegisOps/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+AegisOps",
    "repositoryUrl": "https://github.com/KIM3310/AegisOps",
    "architectureUrl": "https://github.com/KIM3310/AegisOps/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/AegisOps/blob/main/docs/revenue-architecture.md",
    "offer": "incident replay copilot with evidence capture, runbook drafting, and post-incident summary export",
    "freeEntry": "public replay demo plus downloadable incident-readout template",
    "paidSku": "team workspace for incident packs, replay history, export branding, and private provider keys",
    "primaryQuery": "AegisOps incident replay copilot",
    "category": "BusinessApplication"
  },
  {
    "repo": "KIM3310",
    "name": "KIM3310",
    "canonicalUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/KIM3310/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+KIM3310",
    "repositoryUrl": "https://github.com/KIM3310/KIM3310",
    "architectureUrl": "https://github.com/KIM3310/KIM3310/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/KIM3310/blob/main/docs/revenue-architecture.md",
    "offer": "systems catalog that routes visitors to runnable demos, architecture packs, and productized service templates",
    "freeEntry": "public architecture index with free system diagrams and deployment notes",
    "paidSku": "paid implementation package, architecture adaptation package, or template bundle attached to selected systems",
    "primaryQuery": "KIM3310 systems catalog routes",
    "category": "DeveloperApplication"
  },
  {
    "repo": "Nexus-Hive",
    "name": "Nexus Hive",
    "canonicalUrl": "https://nexus-hive.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/Nexus-Hive/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Nexus+Hive",
    "repositoryUrl": "https://github.com/KIM3310/Nexus-Hive",
    "architectureUrl": "https://github.com/KIM3310/Nexus-Hive/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/Nexus-Hive/blob/main/docs/revenue-architecture.md",
    "offer": "governed query gateway with policy checks, semantic metadata, audit logs, and warehouse adapter contracts",
    "freeEntry": "public governed analytics demo over synthetic sales data",
    "paidSku": "paid private connector pack for Snowflake/Databricks/Postgres plus audit export bundle",
    "primaryQuery": "Nexus Hive governed query gateway",
    "category": "BusinessApplication"
  },
  {
    "repo": "SteadyTap",
    "name": "SteadyTap",
    "canonicalUrl": "https://steadytap.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/SteadyTap/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+SteadyTap",
    "repositoryUrl": "https://github.com/KIM3310/SteadyTap",
    "architectureUrl": "https://github.com/KIM3310/SteadyTap/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/SteadyTap/blob/main/docs/revenue-architecture.md",
    "offer": "calibration and adaptive touch challenge toolkit with coach planning and cloud sync option",
    "freeEntry": "free local-first mobile demo and static explainer",
    "paidSku": "premium progress history, organization dashboard, and private calibration templates",
    "primaryQuery": "SteadyTap calibration adaptive touch",
    "category": "HealthApplication"
  },
  {
    "repo": "agent-orchestration-benchmark",
    "name": "Agent Orchestration Benchmark",
    "canonicalUrl": "https://kim3310.github.io/agent-orchestration-benchmark/",
    "leadCaptureUrl": "https://github.com/KIM3310/agent-orchestration-benchmark/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Agent+Orchestration+Benchmark",
    "repositoryUrl": "https://github.com/KIM3310/agent-orchestration-benchmark",
    "architectureUrl": "https://github.com/KIM3310/agent-orchestration-benchmark/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/agent-orchestration-benchmark/blob/main/docs/revenue-architecture.md",
    "offer": "benchmark harness and report generator for agent orchestration reliability",
    "freeEntry": "free benchmark methodology and sample leaderboard",
    "paidSku": "paid benchmark report pack, private scenario suite, and recurring provider regression dashboard",
    "primaryQuery": "Agent Orchestration Benchmark harness generator reliability",
    "category": "DeveloperApplication"
  },
  {
    "repo": "agent-runtime-go",
    "name": "Agent Runtime Go",
    "canonicalUrl": "https://kim3310.github.io/agent-runtime-go/",
    "leadCaptureUrl": "https://github.com/KIM3310/agent-runtime-go/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Agent+Runtime+Go",
    "repositoryUrl": "https://github.com/KIM3310/agent-runtime-go",
    "architectureUrl": "https://github.com/KIM3310/agent-runtime-go/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/agent-runtime-go/blob/main/docs/revenue-architecture.md",
    "offer": "small Go runtime for retries, validation, provider adapters, and inspectable execution traces",
    "freeEntry": "open-source runtime plus quickstart examples",
    "paidSku": "hosted trace console, team policy registry, and enterprise adapter support",
    "primaryQuery": "Agent Runtime Go small retries validation",
    "category": "DeveloperApplication"
  },
  {
    "repo": "ai-agent-production-lab",
    "name": "AI Agent Production Lab",
    "canonicalUrl": "https://kim3310.github.io/ai-agent-production-lab/",
    "leadCaptureUrl": "https://github.com/KIM3310/ai-agent-production-lab/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+AI+Agent+Production+Lab",
    "repositoryUrl": "https://github.com/KIM3310/ai-agent-production-lab",
    "architectureUrl": "https://github.com/KIM3310/ai-agent-production-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/ai-agent-production-lab/blob/main/docs/revenue-architecture.md",
    "offer": "production-readiness lab with guardrails, tracing, deployment checklist, and report artifacts",
    "freeEntry": "free production checklist and sample report",
    "paidSku": "paid readiness report, hardened template pack, and hosted scorecard dashboard",
    "primaryQuery": "AI Agent Production Lab production-readiness guardrails tracing",
    "category": "DeveloperApplication"
  },
  {
    "repo": "ai-security-redteam-lab",
    "name": "AI Security Redteam Lab",
    "canonicalUrl": "https://kim3310.github.io/ai-security-redteam-lab/",
    "leadCaptureUrl": "https://github.com/KIM3310/ai-security-redteam-lab/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+AI+Security+Redteam+Lab",
    "repositoryUrl": "https://github.com/KIM3310/ai-security-redteam-lab",
    "architectureUrl": "https://github.com/KIM3310/ai-security-redteam-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/ai-security-redteam-lab/blob/main/docs/revenue-architecture.md",
    "offer": "red-team scenario runner with risk taxonomy, prompt attack cases, and mitigation reports",
    "freeEntry": "public sample attack catalog and static report",
    "paidSku": "private red-team scenario suite and recurring scan report dashboard",
    "primaryQuery": "AI Security Redteam Lab red-team scenario runner",
    "category": "SecurityApplication"
  },
  {
    "repo": "aix-pilot",
    "name": "AIX Pilot",
    "canonicalUrl": "https://aix-pilot.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/aix-pilot/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+AIX+Pilot",
    "repositoryUrl": "https://github.com/KIM3310/aix-pilot",
    "architectureUrl": "https://github.com/KIM3310/aix-pilot/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/aix-pilot/blob/main/docs/revenue-architecture.md",
    "offer": "enterprise GenAI pilot console with RAG fixtures, DLP masking, KPI views, and evaluation flows",
    "freeEntry": "public Cloudflare Pages demo with synthetic fixtures",
    "paidSku": "paid pilot workspace with private docs, provider keys, KPI dashboards, and exportable business case",
    "primaryQuery": "AIX Pilot enterprise GenAI console",
    "category": "BusinessApplication"
  },
  {
    "repo": "beaver-study-orchestrator",
    "name": "Beaver Study Orchestrator",
    "canonicalUrl": "https://kim3310.github.io/beaver-study-orchestrator/",
    "leadCaptureUrl": "https://github.com/KIM3310/beaver-study-orchestrator/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Beaver+Study+Orchestrator",
    "repositoryUrl": "https://github.com/KIM3310/beaver-study-orchestrator",
    "architectureUrl": "https://github.com/KIM3310/beaver-study-orchestrator/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/beaver-study-orchestrator/blob/main/docs/revenue-architecture.md",
    "offer": "study orchestration board with planning, outcomes, history, and adaptive next steps",
    "freeEntry": "free local study planner and public demo",
    "paidSku": "premium study history, cohort dashboard, and exportable progress report",
    "primaryQuery": "Beaver Study Orchestrator orchestration board planning",
    "category": "EducationalApplication"
  },
  {
    "repo": "districtpilot-ai",
    "name": "Districtpilot AI",
    "canonicalUrl": "https://kim3310.github.io/districtpilot-ai/",
    "leadCaptureUrl": "https://github.com/KIM3310/districtpilot-ai/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Districtpilot+AI",
    "repositoryUrl": "https://github.com/KIM3310/districtpilot-ai",
    "architectureUrl": "https://github.com/KIM3310/districtpilot-ai/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/districtpilot-ai/blob/main/docs/revenue-architecture.md",
    "offer": "district operations planning and public API readiness explorer",
    "freeEntry": "public static district planning demo with architecture notes",
    "paidSku": "paid readiness report, data connector pack, and private planning workspace",
    "primaryQuery": "Districtpilot AI district operations planning",
    "category": "BusinessApplication"
  },
  {
    "repo": "doeon-kim-portfolio",
    "name": "KIM3310 Systems Gallery",
    "canonicalUrl": "https://kim3310-doeon-kim-portfolio.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/doeon-kim-portfolio/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+KIM3310+Systems+Gallery",
    "repositoryUrl": "https://github.com/KIM3310/doeon-kim-portfolio",
    "architectureUrl": "https://github.com/KIM3310/doeon-kim-portfolio/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/doeon-kim-portfolio/blob/main/docs/revenue-architecture.md",
    "offer": "product storefront for architecture packs, demos, and implementation-ready systems",
    "freeEntry": "free systems gallery with live demos and architecture links",
    "paidSku": "paid architecture pack bundle, implementation sprint, or private adaptation of a repo",
    "primaryQuery": "KIM3310 Systems Gallery product storefront architecture",
    "category": "DeveloperApplication"
  },
  {
    "repo": "dream-interpretation-pages",
    "name": "Dream Interpretation Pages",
    "canonicalUrl": "https://kim3310.github.io/dream-interpretation-pages/",
    "leadCaptureUrl": "https://github.com/KIM3310/dream-interpretation-pages/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Dream+Interpretation+Pages",
    "repositoryUrl": "https://github.com/KIM3310/dream-interpretation-pages",
    "architectureUrl": "https://github.com/KIM3310/dream-interpretation-pages/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/dream-interpretation-pages/blob/main/docs/revenue-architecture.md",
    "offer": "dream interpretation pages with private journaling, symbolic prompts, and shareable report cards",
    "freeEntry": "free interpretation page with limited daily reports",
    "paidSku": "premium saved journal, long-form reports, themes, and export packs",
    "primaryQuery": "Dream Interpretation Pages journaling symbolic prompts",
    "category": "LifestyleApplication"
  },
  {
    "repo": "enterprise-llm-adoption-kit",
    "name": "Enterprise LLM Adoption Kit",
    "canonicalUrl": "https://enterprise-llm-kit.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/enterprise-llm-adoption-kit/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Enterprise+LLM+Adoption+Kit",
    "repositoryUrl": "https://github.com/KIM3310/enterprise-llm-adoption-kit",
    "architectureUrl": "https://github.com/KIM3310/enterprise-llm-adoption-kit/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/enterprise-llm-adoption-kit/blob/main/docs/revenue-architecture.md",
    "offer": "adoption kit with governance controls, workshop assets, service briefs, evals, and control tower surfaces",
    "freeEntry": "public templates, service brief samples, and architecture docs",
    "paidSku": "paid workshop pack, private control tower deployment, and governance evidence bundle",
    "primaryQuery": "Enterprise LLM Adoption Kit governance controls workshop",
    "category": "BusinessApplication"
  },
  {
    "repo": "fab-ops-yield-control-tower",
    "name": "Fab Ops Yield Control Tower",
    "canonicalUrl": "https://fab-ops-yield-control-tower.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/fab-ops-yield-control-tower/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Fab+Ops+Yield+Control+Tower",
    "repositoryUrl": "https://github.com/KIM3310/fab-ops-yield-control-tower",
    "architectureUrl": "https://github.com/KIM3310/fab-ops-yield-control-tower/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/fab-ops-yield-control-tower/blob/main/docs/revenue-architecture.md",
    "offer": "yield control tower with alarm triage, lot risk, release gates, and shift handoff",
    "freeEntry": "public synthetic fab demo and operating model",
    "paidSku": "paid factory pilot workspace with private connectors and shift report export",
    "primaryQuery": "Fab Ops Yield Control Tower alarm triage lot",
    "category": "BusinessApplication"
  },
  {
    "repo": "kbbq-idle-unity",
    "name": "KBBQ Idle Unity",
    "canonicalUrl": "https://kbbq-idle-unity.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/kbbq-idle-unity/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+KBBQ+Idle+Unity",
    "repositoryUrl": "https://github.com/KIM3310/kbbq-idle-unity",
    "architectureUrl": "https://github.com/KIM3310/kbbq-idle-unity/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/kbbq-idle-unity/blob/main/docs/revenue-architecture.md",
    "offer": "Korean BBQ idle game with progression, leaderboard, events, and collectible content",
    "freeEntry": "free WebGL build on Pages/itch.io",
    "paidSku": "cosmetic packs, ad-free mode, event boosts, and supporter bundle",
    "primaryQuery": "KBBQ Idle Unity Korean BBQ game",
    "category": "GameApplication"
  },
  {
    "repo": "lakehouse-contract-lab",
    "name": "Lakehouse Contract Lab",
    "canonicalUrl": "https://kim3310.github.io/lakehouse-contract-lab/",
    "leadCaptureUrl": "https://github.com/KIM3310/lakehouse-contract-lab/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Lakehouse+Contract+Lab",
    "repositoryUrl": "https://github.com/KIM3310/lakehouse-contract-lab",
    "architectureUrl": "https://github.com/KIM3310/lakehouse-contract-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/lakehouse-contract-lab/blob/main/docs/revenue-architecture.md",
    "offer": "lakehouse contract compiler, quality gate, artifact builder, and export adapter lab",
    "freeEntry": "free synthetic pipeline and contract examples",
    "paidSku": "paid connector templates, contract migration pack, and recurring data quality report",
    "primaryQuery": "Lakehouse Contract Lab compiler quality gate",
    "category": "DeveloperApplication"
  },
  {
    "repo": "llm-onprem-deployment-kit",
    "name": "LLM On-Prem Deployment Kit",
    "canonicalUrl": "https://kim3310.github.io/llm-onprem-deployment-kit/",
    "leadCaptureUrl": "https://github.com/KIM3310/llm-onprem-deployment-kit/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+LLM+On-Prem+Deployment+Kit",
    "repositoryUrl": "https://github.com/KIM3310/llm-onprem-deployment-kit",
    "architectureUrl": "https://github.com/KIM3310/llm-onprem-deployment-kit/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/llm-onprem-deployment-kit/blob/main/docs/revenue-architecture.md",
    "offer": "deployment kit for Kubernetes, Helm, Terraform, observability, and security controls",
    "freeEntry": "free reference architecture and Helm/Terraform starter kit",
    "paidSku": "paid private deployment support, hardened values pack, and upgrade runbook subscription",
    "primaryQuery": "LLM On-Prem Deployment Kit Kubernetes Helm Terraform",
    "category": "DeveloperApplication"
  },
  {
    "repo": "multi-cli-pilot",
    "name": "Multi-CLI Pilot",
    "canonicalUrl": "https://kim3310.github.io/multi-cli-pilot/",
    "leadCaptureUrl": "https://github.com/KIM3310/multi-cli-pilot/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Multi-CLI+Pilot",
    "repositoryUrl": "https://github.com/KIM3310/multi-cli-pilot",
    "architectureUrl": "https://github.com/KIM3310/multi-cli-pilot/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/multi-cli-pilot/blob/main/docs/revenue-architecture.md",
    "offer": "multi-CLI orchestration runner with reproducible task routes and provider abstraction",
    "freeEntry": "free CLI recipes and demo tasks",
    "paidSku": "team workflow library, hosted run history, and provider cost dashboard",
    "primaryQuery": "Multi-CLI Pilot orchestration runner reproducible",
    "category": "DeveloperApplication"
  },
  {
    "repo": "nw-service-assurance-workbench",
    "name": "NW Service Assurance Workbench",
    "canonicalUrl": "https://nw-service-assurance-workbench.ehdjs1351.workers.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/nw-service-assurance-workbench/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+NW+Service+Assurance+Workbench",
    "repositoryUrl": "https://github.com/KIM3310/nw-service-assurance-workbench",
    "architectureUrl": "https://github.com/KIM3310/nw-service-assurance-workbench/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/nw-service-assurance-workbench/blob/main/docs/revenue-architecture.md",
    "offer": "network service assurance workbench with SLA signals, service paths, and incident handoff",
    "freeEntry": "public synthetic network operations demo",
    "paidSku": "paid workspace for service maps, private incident history, and recurring SLA reports",
    "primaryQuery": "NW Service Assurance Workbench network SLA signals",
    "category": "BusinessApplication"
  },
  {
    "repo": "quantum-workbench",
    "name": "Quantum Workbench",
    "canonicalUrl": "https://kim3310.github.io/quantum-workbench/",
    "leadCaptureUrl": "https://github.com/KIM3310/quantum-workbench/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Quantum+Workbench",
    "repositoryUrl": "https://github.com/KIM3310/quantum-workbench",
    "architectureUrl": "https://github.com/KIM3310/quantum-workbench/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/quantum-workbench/blob/main/docs/revenue-architecture.md",
    "offer": "quantum experiment workbench with provider adapters, job inspection, and educational reports",
    "freeEntry": "free simulator-first demo and static architecture page",
    "paidSku": "paid lab workspace, course bundle, and provider-cost planning reports",
    "primaryQuery": "Quantum Workbench experiment provider adapters",
    "category": "EducationalApplication"
  },
  {
    "repo": "retina-scan-ai",
    "name": "Retina Scan AI",
    "canonicalUrl": "https://kim3310.github.io/retina-scan-ai/",
    "leadCaptureUrl": "https://github.com/KIM3310/retina-scan-ai/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Retina+Scan+AI",
    "repositoryUrl": "https://github.com/KIM3310/retina-scan-ai",
    "architectureUrl": "https://github.com/KIM3310/retina-scan-ai/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/retina-scan-ai/blob/main/docs/revenue-architecture.md",
    "offer": "retinal classification research demo with Grad-CAM style explainability and compliance notes",
    "freeEntry": "free static research demo with non-diagnostic framing",
    "paidSku": "paid education workspace, research report pack, and private dataset evaluation support",
    "primaryQuery": "Retina Scan AI retinal classification research",
    "category": "EducationalApplication"
  },
  {
    "repo": "secure-xl2hwp-local",
    "name": "Secure XL2HWP Local",
    "canonicalUrl": "https://secure-xl2hwp-local.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/secure-xl2hwp-local/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Secure+XL2HWP+Local",
    "repositoryUrl": "https://github.com/KIM3310/secure-xl2hwp-local",
    "architectureUrl": "https://github.com/KIM3310/secure-xl2hwp-local/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/secure-xl2hwp-local/blob/main/docs/revenue-architecture.md",
    "offer": "local-only spreadsheet cleanup and Hancom handoff workflow with signed audit/export evidence",
    "freeEntry": "public architecture page that explains trust boundary and handoff path",
    "paidSku": "paid local license, deployment package, and template adaptation support",
    "primaryQuery": "Secure XL2HWP Local local-only spreadsheet cleanup",
    "category": "BusinessApplication"
  },
  {
    "repo": "security-threat-response-workbench",
    "name": "Security Threat Response Workbench",
    "canonicalUrl": "https://security-threat-response-workbench.ehdjs1351.workers.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/security-threat-response-workbench/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Security+Threat+Response+Workbench",
    "repositoryUrl": "https://github.com/KIM3310/security-threat-response-workbench",
    "architectureUrl": "https://github.com/KIM3310/security-threat-response-workbench/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/security-threat-response-workbench/blob/main/docs/revenue-architecture.md",
    "offer": "threat response workbench with scenario board, runbooks, indicators, and snapshot reports",
    "freeEntry": "public synthetic threat-response demo",
    "paidSku": "paid private scenario workspace and recurring threat exercise report",
    "primaryQuery": "Security Threat Response Workbench scenario board runbooks",
    "category": "SecurityApplication"
  },
  {
    "repo": "stage-pilot",
    "name": "StagePilot",
    "canonicalUrl": "https://stage-pilot.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/stage-pilot/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+StagePilot",
    "repositoryUrl": "https://github.com/KIM3310/stage-pilot",
    "architectureUrl": "https://github.com/KIM3310/stage-pilot/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/stage-pilot/blob/main/docs/revenue-architecture.md",
    "offer": "tool-calling reliability gateway with regression tests, provider scorecards, and trace observability",
    "freeEntry": "free public benchmark/demo routes and sample traces",
    "paidSku": "paid hosted regression workspace, private benchmark scenarios, and provider routing dashboard",
    "primaryQuery": "StagePilot tool-calling reliability gateway",
    "category": "DeveloperApplication"
  },
  {
    "repo": "the-savior",
    "name": "The Savior",
    "canonicalUrl": "https://kim3310.github.io/the-savior/",
    "leadCaptureUrl": "https://github.com/KIM3310/the-savior/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+The+Savior",
    "repositoryUrl": "https://github.com/KIM3310/the-savior",
    "architectureUrl": "https://github.com/KIM3310/the-savior/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/the-savior/blob/main/docs/revenue-architecture.md",
    "offer": "ambient reflection app with guided prompts, candle visuals, and shareable runtime brief",
    "freeEntry": "free static ritual experience",
    "paidSku": "premium theme packs, private journal export, and supporter bundle",
    "primaryQuery": "The Savior ambient reflection app",
    "category": "LifestyleApplication"
  },
  {
    "repo": "tool-call-finetune-lab",
    "name": "Tool-Call Fine-Tune Lab",
    "canonicalUrl": "https://kim3310.github.io/tool-call-finetune-lab/",
    "leadCaptureUrl": "https://github.com/KIM3310/tool-call-finetune-lab/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Tool-Call+Fine-Tune+Lab",
    "repositoryUrl": "https://github.com/KIM3310/tool-call-finetune-lab",
    "architectureUrl": "https://github.com/KIM3310/tool-call-finetune-lab/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/tool-call-finetune-lab/blob/main/docs/revenue-architecture.md",
    "offer": "fine-tuning and eval pipeline for tool-call datasets, BFCL-style tests, and serving checks",
    "freeEntry": "free open-source pipeline and sample eval reports",
    "paidSku": "paid dataset preparation pack, eval report, and private fine-tuning runbook",
    "primaryQuery": "Tool-Call Fine-Tune Lab fine-tuning eval pipeline",
    "category": "DeveloperApplication"
  },
  {
    "repo": "twincity-ui",
    "name": "TwinCity UI",
    "canonicalUrl": "https://twincity-ui.pages.dev/",
    "leadCaptureUrl": "https://github.com/KIM3310/twincity-ui/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+TwinCity+UI",
    "repositoryUrl": "https://github.com/KIM3310/twincity-ui",
    "architectureUrl": "https://github.com/KIM3310/twincity-ui/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/twincity-ui/blob/main/docs/revenue-architecture.md",
    "offer": "digital twin operations console with replay, dispatch, readiness, and report surfaces",
    "freeEntry": "public demo with synthetic city/facility events",
    "paidSku": "paid workspace for private maps, event ingestion, and monthly readiness reports",
    "primaryQuery": "TwinCity UI digital twin operations",
    "category": "BusinessApplication"
  },
  {
    "repo": "weld-defect-vision",
    "name": "Weld Defect Vision",
    "canonicalUrl": "https://kim3310.github.io/weld-defect-vision/",
    "leadCaptureUrl": "https://github.com/KIM3310/weld-defect-vision/issues/new?template=service-inquiry.yml&title=Private+workspace+inquiry%3A+Weld+Defect+Vision",
    "repositoryUrl": "https://github.com/KIM3310/weld-defect-vision",
    "architectureUrl": "https://github.com/KIM3310/weld-defect-vision/blob/main/docs/system-architecture.md",
    "revenueUrl": "https://github.com/KIM3310/weld-defect-vision/blob/main/docs/revenue-architecture.md",
    "offer": "weld defect detection demo with dataset validation, model serving, and explainable inspection report",
    "freeEntry": "free static inspection demo and architecture page",
    "paidSku": "paid private dataset evaluation, model card/report pack, and edge deployment package",
    "primaryQuery": "Weld Defect Vision detection dataset validation",
    "category": "BusinessApplication"
  }
] as const;

export type ServiceOffer = (typeof SERVICE_OFFERS)[number];
