/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=PagesEnv types/pages-env.d.ts` (hash: 19e4bc071e1aa4dfc2624551ffac9299)
interface __BaseEnv_PagesEnv {
	LEADS_DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_PagesEnv {}
}
interface PagesEnv extends __BaseEnv_PagesEnv {}
