/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=PagesEnv types/pages-env.d.ts` (hash: 1ae3b9a80e5bd3fe831d20ce0bc8334d)
interface __BaseEnv_PagesEnv {
	LEADS_DB: D1Database;
	FIREBASE_PROJECT_ID: "kim3310-free-tools";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_PagesEnv {}
}
interface PagesEnv extends __BaseEnv_PagesEnv {}
