/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.retention.jsonc --include-runtime=false --env-interface=RetentionEnv types/retention-env.d.ts` (hash: 8c8d08b37efe440e1a880f4b9c1ca931)
interface __BaseEnv_RetentionEnv {
	LEADS_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../workers/inquiry-retention");
	}
	interface Env extends __BaseEnv_RetentionEnv {}
}
interface RetentionEnv extends __BaseEnv_RetentionEnv {}
